---
# Install MySQL server.
- name: Install MySQL server and Python MySQLdb connector.
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - mysql-common
    - mysql-server
    - python-mysqldb

# Ensure that MySQL daemon starts with the system.
- name: Ensure MySQL is enabled on boot
  service:
    name: mysql
    enabled: yes

- name: Check whether MySQL service is running
  command: service mysql status
  register: mysql_service_status
  args:
    warn: false
  failed_when: false
  changed_when: false

- name: Ensure MySQL is started
  command: service mysql start
  when: "'MySQL is stopped' in mysql_service_status.stdout"
  # Skip Ansible Lint check, as service module fails to start MySQL on Ubuntu
  # Trusty in a Docker container (because upstart doesn't work).
  args:
    warn: false

# Has to be after the root password assignment, for idempotency.
- name: Copy .my.cnf file with root password credentials.
  template:
    src: "root-my.cnf.j2"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Create default database
  mysql_db:
    name: drupal
    collation: utf8mb4_general_ci
    encoding: utf8mb4

- name: Create default database user
  mysql_user:
    name: drupal
    password: drupal
    priv: drupal.*:ALL
