version: 2
updates:
  # Maintain dependencies for Composer.
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    allow:
      # Allow direct & indirect updates for all packages.
      - dependency-type: "all"
    commit-message:
      prefix: "Updates "
      include: scope
    target-branch: 3.x.x
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
