---
- name: Set timezone
  timezone:
    name: '{{ vagrant.timezone }}'

- name: Ensure base packages are installed
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - curl
    - git
    - rsyslog
    - tzdata
    - unzip
    - wget

- name: Add vagrant user to syslog group
  user:
    name: vagrant
    groups: syslog
    append: yes

- name: Ensure that logs directories exist
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    group: vagrant
    owner: vagrant
  with_items:
    - /var/log/draft

# Required by Deamonize, which is required by MailHog
- name: Ensure build-essential package is installed
  apt:
    name: build-essential
    state: present
  when: "'mailhog' in draft_features"

- name: Add Composer bin directory to global $PATH
  template:
    src: vendor_path.sh.j2
    dest: /etc/profile.d/vendor_path.sh
    mode: 0644

- name: Use Vagrant base directory as a default SSH directory
  become: true
  become_user: vagrant
  lineinfile:
    path: ~/.bashrc
    line: cd {{ ssh_default_directory }}
