---

# PHP extensions to install.
php_extensions:
  - curl
  - gd
  - json
  - mbstring
  - mysql
  - sqlite3
  - xdebug
  - xml
  - zip

# Configure PHP.
php_configuration:
  PHP:
    error_reporting: E_ALL
    error_log: /var/log/draft/php_error.log
    display_errors: 'On'
    display_startup_errors: 'On'
    memory_limit: 256M
    output_buffering: 'Off'
    upload_max_filesize: 64M
    post_max_size: 512M

# Configure PHP extensions.
php_extensions_configuration:
  opcache:
    opcache.error_log: /var/log/draft/php_opcache_error.log
  xdebug:
    xdebug.remote_enable: 'On'
    xdebug.remote_connect_back: 'On'
    xdebug.remote_log: /var/log/draft/php_xdebug_remote.log
