---
# This is exact copy of main playbook, except oefenweb.swapfile is skipped
# because it's not possible to test it on Travis CI. Also we manually add
# vagrant user as it does not exist in Docker.
- hosts: all
  become: true

  pre_tasks:

    # Molecule does not use our Vagrantfile. Let's fill the gap.
    - name: Add missing variables
      set_fact:
        vagrant: "{{ vagrant | combine(overrides, recursive=true) }}"
        draft_features:
          - mailhog
          - git_config
          - apache2
          - mysql
          - php
          - composer
          - java
          - solr
      vars:
        overrides:
          hostname: molecule
          ip_address: 10.10.10.10


    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

  roles:
    - ../../provisioning/roles/draft
    - ../../provisioning/roles/git_config
    - ../../provisioning/roles/apache2
    - geerlingguy.mysql
    - geerlingguy.mailhog
    - t2l.php
    - t2l.composer
    - t2l.java
    - t2l.solr
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../../default.vm-settings.yml
