---
dependency:
  name: galaxy
  options:
    roles-path: ~/.ansible/roles
    role-file: provisioning/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: draft
    image: ubuntu:${MOLECULE_PLATFORM}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/ansible
verifier:
  name: ansible
