---
dependency:
  name: galaxy
  options:
    roles-path: ~/.ansible/roles
    role-file: provisioning/requirements.yml
driver:
  name: vagrant
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: draft
    box: ubuntu/${MOLECULE_PLATFORM}
    memory: 1024
    cpus: 2
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/ansible
    ssh_connection:
      pipelining: true
verifier:
  name: ansible
