---
# Install apache2.
- name: Install Apache2 web server
  apt:
    name:
      - apache2
      - openssl
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: Enable Apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - expires
    - headers
    - rewrite
    - ssl
  notify:
    - Restart Apache2 web server

- name: Ensure that directory for SSL keys exist
  file:
    path: /etc/apache2/ssl
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create OpenSSL config file
  template:
    src: draft-ssl-config.ini.j2
    dest: /etc/apache2/ssl/draft-ssl-config.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Apache2 web server
  register: draft_ssl_config_file
  when:
    mkcert is not defined

- name: Generate SSL keys
  command: |
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048
    -config /etc/apache2/ssl/draft-ssl-config.ini
    -keyout /etc/apache2/ssl/draft.key
    -out /etc/apache2/ssl/draft.crt
  notify:
    - Restart Apache2 web server
  when:
    mkcert is not defined and draft_ssl_config_file is changed
  # Skip Ansible Lint check. This should not be a handler.
  tags:
    - skip_ansible_lint

- name: Copy mkcert certificate and key to the host ssl folder
  copy:
    src: /tmp/mkcert/
    dest: /etc/apache2/ssl
    remote_src: true
    mode: 0644
  notify:
    - Restart Apache2 web server
  when:
    mkcert is defined

- name: Ensure that document directory exist
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ vagrant.destination_directory }}/{{ apache2_document_root }}'

- name: Get /etc/apache2/mods-available/dir.conf permissions
  stat:
    path: /etc/apache2/mods-available/dir.conf
    get_checksum: false
    get_mime: false
  register: dir_conf_stat

# Configure web server.
- name: Set correct DirectoryIndex
  lineinfile:
    dest: /etc/apache2/mods-available/dir.conf
    regexp: "DirectoryIndex"
    line: "DirectoryIndex index.php index.html"
    mode: '{{ dir_conf_stat.stat.mode }}'

# Disable default virtual host created on Ubuntu/Debian.
- name: Disable default virtual host.
  command: a2dissite 000-default
  register: apache2_disable_default_virtual_host_result
  changed_when: "'Site 000-default disabled.' in apache2_disable_default_virtual_host_result.stdout"
  notify:
    - Restart Apache2 web server

# Add custom virtual host.
- name: Add custom virtual host.
  template:
    src: "draft.conf.j2"
    dest: "/etc/apache2/sites-available/draft.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Apache2 web server

- name: Enable custom virtual host.
  command: a2ensite draft
  register: apache2_enable_custom_virtual_host_result
  changed_when: "'Enabling site draft.' in apache2_enable_custom_virtual_host_result.stdout"
  notify:
    - Restart Apache2 web server

- name: Ensure that Apache 'sees' system environment
  ansible.builtin.lineinfile:
    path: /etc/apache2/envvars
    line: '. /etc/environment'
  notify:
    - Restart Apache2 web server

# Ensure that apache2 daemon starts with the system.
- name: Ensure Apache2 is started and enabled on boot.
  service:
    name: apache2
    state: started
    enabled: true
