---
- src: oefenweb.swapfile
  version: v2.0.32
- src: geerlingguy.mailhog
  version: 2.2.0
- src: geerlingguy.mysql
  version: 3.3.0
- src: t2l.php
  version: 1.4.0
- src: t2l.composer
  version: 2.0.3
- src: t2l.java
  version: 1.3.2
- src: t2l.solr
  version: 2.2.2
