---
- src: oefenweb.swapfile
  version: v2.0.7
- src: geerlingguy.mailhog
  version: 2.1.4
- src: T2L.php
  version: 1.1.1
- src: T2L.composer
  version: 2.0.2
- src: T2L.java
  version: 1.1.0
- src: T2L.solr
  version: 2.0.0
